# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SwitchLayers
                                 A QGIS plugin
 This plugin switches the layers that are grouped
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-16
        copyright            : (C) 2023 by Murat Sahin
        email                : sahinmurat3@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SwitchLayers class from file SwitchLayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .switch_layers import SwitchLayers
    return SwitchLayers(iface)
